//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Проживание
    {
        public int КодПроживания { get; set; }
        public System.DateTime ДатаЗаселения { get; set; }
        public System.DateTime ДатаВыселения { get; set; }
        public double Стоимость { get; set; }
        public System.DateTime ДатаОплаты { get; set; }
        public int КодНомера { get; set; }
        public int КодКлиента { get; set; }
        public Nullable<int> КодБронирования { get; set; }
    
        public virtual Бронирование Бронирование { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        public virtual Номера Номера { get; set; }
    }
}
